[project]
name = "students_performance"
version = "0.0.0"
dependencies = [
    "ipykernel",
    "pandas==2.3.0",
    "pyarrow==20.0.0",
    "fastparquet==2024.11.0",
    "torch==2.7.0",
    "scikit-learn==1.7.0",
    "python-dotenv==1.1.0",
    "mlflow==3.0.0",
    "tqdm==4.67.1"
]
