[project]
name = "students_performance"
version = "0.0.0"
dependencies = [
    "ipykernel",
    "pandas==2.3.0",
    "pyarrow==20.0.0",
    "fastparquet==2024.11.0",
    "torch==2.3.0",
    "scikit-learn==1.7.0"
]